apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: haloserver.azurecr.io/halo-configserver-v1.0.0:M01-2023-02-07-1003-develop-optix-B1102
        # image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
        args: [ "bash", "-c", "cd /usr/local/ofs/conf && ./haloserver start && /bin/bash" ]
        env:
        - name: INSTANCE_HOST
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TIMEZONE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8443
          - containerPort: 8444
          - containerPort: 8080
        resources:
          requests:
            cpu: 0.3
            memory: 3Gi
            #cpu: 200m
            #memory: 128Mi
          limits:
            #cpu: 350m
            #memory: 256Mi
            cpu: 0.6
            memory: 3Gi
        stdin: true
        tty: true
        volumeMounts:
          - name: shared
            mountPath: "/usr/local/ofs/conf/shared/"
          - name: workspace
            mountPath: "/usr/local/ofs/conf/workspace/"
          - name: logs
            mountPath: "/usr/local/ofs/log/"
      imagePullSecrets:
      - name: haloserver-acr-secret
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc